---
- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'

- name: 'Pip'
  when: avenv_manager | lower == 'pip'
  ansible.builtin.include_tasks: 'pip.yml'

- name: 'UV'
  when: avenv_manager | lower == 'uv'
  ansible.builtin.include_tasks: 'uv.yml'
