---
###############################################################################
# Ansible-VENV Prep
###############################################################################
# Create venv full path and determine if setuptools is required because of
# executable option.
#
# Generates:
#   _avenv_setuptools_required: bool - setuptools package required.
#
# Exports:
#   _avenv_venv: str - absolute path to venv directory.

- name: 'Prep | sanitize options'
  ansible.builtin.set_fact:
    _avenv_venv: '{{
        avenv_config_dir
        if avenv_config_dir.endswith("/") else
        avenv_config_dir ~ "/"
      }}{{ avenv_name }}'
    _avenv_setuptools_required: '{{
        avenv_pips or avenv_uv_pips | default([]) |
        map(attribute="executable") | length > 0
      }}'

- name: 'Prep | create config directory'
  ansible.builtin.file:
    path: '{{ avenv_config_dir }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

- name: 'Prep | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ avenv_role_packages }}'
      - '{{ avenv_packages }}'
      - '{{
          avenv_role_packages_setuptools
          if _avenv_setuptools_required else
          []
        }}'
    apt_packages_absent:
      - '{{ avenv_packages_absent }}'
    apt_sources: '{{ avenv_apt_sources }}'
    apt_package_update_cache: true

- name: 'Prep | create virtual environment root'
  ansible.builtin.file:
    path: '{{ _avenv_venv }}'
    owner: '{{ avenv_user }}'
    group: '{{ avenv_group }}'
    mode: '0750'
    state: 'directory'
