---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.deb.avenv (pip)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.avenv'
      vars:
        avenv_name: 'pip'
        avenv_manager: 'pip'

    - name: 'Converge | apply r_pufky.deb.avenv (uv)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.avenv'
      vars:
        avenv_name: 'uv'
        avenv_manager: 'uv'
