---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare | cache'

    - name: 'Prepare | check UV 0.7.8'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Prepare | check UV 0.7.8'
        test_dest: 'uv-x86_64-unknown-linux-gnu.tar.gz'
        test_url: '{{
            "https://github.com/astral-sh/uv/releases/download/" ~
            "0.7.8/" ~
            "uv-x86_64-unknown-linux-gnu.tar.gz"
          }}'
        test_mode: '0750'

    - name: 'Prepare | check UV 0.7.8 checksum'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Prepare | check UV 0.7.8 checksum'
        test_dest: 'uv-x86_64-unknown-linux-gnu.tar.gz.sha256'
        test_url: '{{
            "https://github.com/astral-sh/uv/releases/download/" ~
            "0.7.8/" ~
            "uv-x86_64-unknown-linux-gnu.tar.gz.sha256"
          }}'
        test_mode: '0640'

- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  become: true
  tasks:
    - name: 'Prepare | set /tmp/requirements.txt'
      ansible.builtin.copy:
        src: '{{
            lookup("env", "MOLECULE_SCENARIO_DIRECTORY") ~
            "/files/requirements_path.txt"
          }}'
        dest: '/tmp/requirements.txt'
        owner: 'root'
        group: 'root'
        mode: '0644'
