---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | /var/venv'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | /var/venv/{{ item }}'
        test_file: '/var/venv/{{ item }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0750'
        test_state: 'directory'
        test_diff: true
      loop:
        - 'pip'
        - 'uv'

    - name: 'Verify | query pip manager packages'
      ansible.builtin.shell: >-
        set -o pipefail &&
        source /var/venv/pip/bin/exec pip list
      args:
        executable: '/bin/bash'
      changed_when: false
      register: _test_avenv_pip

    - name: 'Verify | query uv manager packages'
      ansible.builtin.shell: >-
        set -o pipefail &&
        source /var/venv/uv/bin/exec uv pip list
      args:
        executable: '/bin/bash'
      changed_when: false
      register: _test_avenv_uv

    - name: 'Verify | assert user defined packages'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"stopwords" in _test_avenv_pip.stdout'
          - '"stopwords" in _test_avenv_uv.stdout'
        fail_msg: >
          ✘ stopwords PIP package should be installed.
          ({{ _test_avenv_pip.stdout }})
          ({{ _test_avenv_uv.stdout }}).

    - name: 'Verify | assert controller requirements.txt'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"amqp" in _test_avenv_pip.stdout'
          - '"amqp" in _test_avenv_uv.stdout'
        fail_msg: >
          ✘ amqp PIP package should be installed.
          ({{ _test_avenv_pip.stdout }})
          ({{ _test_avenv_uv.stdout }}).

    - name: 'Verify | assert path requirements.txt'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"anyio" in _test_avenv_pip.stdout'
          - '"anyio" in _test_avenv_uv.stdout'
        fail_msg: >
          ✘ anyio PIP package should be installed.
          ({{ _test_avenv_pip.stdout }})
          ({{ _test_avenv_uv.stdout }}).
